---
title: "Merge lifetime diagnoses datasets"
author: "Molly Davies"
date: "18/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Set up
```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment=NA,
                      prompt=FALSE,
                      cache=FALSE)


options(bitmapType = 'quartz') # to render fonts better
```

Clear global environment
```{r Clear global environment}
remove(list = ls())
```

Retrieve the current date to use it for file endings to not overwrite files when one exports files
```{r Recent date}
date = Sys.Date()
```


Load packages
```{r load packages}
library(tidyverse)
library(skimr)
```

# Read data

```{r source path for reading/saving data}
#Source raw data directory (raw_path) & clean data export directory (cleaned_path)
source("../GLAD_data_path.R")
```

```{r set paths}
#Names
dem_name <- "DEM_cleaned.rds"
mhd_name <- "MHD_cleaned.rds"
CIDID_name <- "CIDID_cleaned.rds"
CIDIA_name <- "CIDIA_cleaned.rds"
SPEC_name <- "SPEC_cleaned.rds"
SOCP_name <- "SOCP_cleaned.rds"
PAD_name <- "PAD_cleaned.rds"
AGP_name <- "AGP_cleaned.rds"

#Files
dem_filename <- paste(cleaned_path, dem_name, sep = "")
mhd_filename <- paste(cleaned_path, mhd_name, sep = "")
CIDID_filename <- paste(cleaned_path, CIDID_name, sep = "")
CIDIA_filename <- paste(cleaned_path, CIDIA_name, sep = "")
SPEC_filename <- paste(cleaned_path, SPEC_name, sep = "")
SOCP_filename <- paste(cleaned_path, SOCP_name, sep = "")
PAD_filename <- paste(cleaned_path, PAD_name, sep = "")
AGP_filename <- paste(cleaned_path, AGP_name, sep = "")

```

# Import data
```{r import data}
dem <- read_rds(dem_filename)
dim(dem)

mhd <- read_rds(mhd_filename)
dim(mhd)

CIDID <- read_rds(CIDID_filename)
dim(CIDID)

CIDIA <- read_rds(CIDIA_filename)
dim(CIDIA)

SPEC <- read_rds(SPEC_filename)
dim(SPEC)

SOCP <- read_rds(SOCP_filename)
dim(SOCP)

PAD <- read_rds(PAD_filename)
dim(PAD)

AGP <- read_rds(AGP_filename)
dim(AGP)
```

Merge the datasets by ID.
```{r merge datasets}
dat <- list(dem,
            mhd,
            CIDID,
            CIDIA,
            SPEC,
            SOCP,
            PAD,
            AGP) %>% 
  reduce(left_join, by = "ID")
```

```{r Skim data}
#look at the data
skimr::skim(dat)
```

```{r Save four cohorts as rds file}
saveRDS(object = dat, file = paste0(cleaned_path, "combined_cleaned.rds"))
```

